services:
  vct-postgres:
    image: postgres:17
    container_name: vct-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - vct_postgres_data:/var/lib/postgresql/data

volumes:
  vct_postgres_data:
